#!/bin/bash

# read arguments
num=$1
outputFile=$2
light=$3
heavy=$4

# run the OSCAR to UrQMD converter
# ftn10 would be light hadron sampled from particlization
# ftn20 would be Dmeson sampled from fragPLUSrecomb
# nsamples would be # of oversamples from hypersurface
#export ftn10=$light
export ftn20=$heavy
osc2u < $light  nsamples=$num > urqmd_input.dat || exit 1

# create UrQMD config file
cat > urqmd.conf <<EOF
# calculate until a late time
# output only the final timestep
tim 8000 8000

# read initial state from file 10
cto 40 2

# write to file 30, suppress all others
f13
f14
f15
f16
f18
f19
f20
#f30

# end of file
xxx
EOF

# run UrQMD
ftn09=urqmd.conf ftn10=urqmd_input.dat ftn30=$outputFile urqmd || exit 1
